# Generated by Django 4.0.3 on 2023-12-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('dni', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_repuesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_repuesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repuesto', models.CharField(max_length=50)),
                ('reparado', models.BooleanField(default=False)),
                ('entrega', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cliente', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
                ('id_tipo_repuesto', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.tiporeparacion')),
            ],
        ),
    ]
