# Generated by Django 4.0.3 on 2023-12-18 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='id_tipo_reparacion',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.tiporeparacion'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='id_tipo_repuesto',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.tiporepuesto'),
        ),
    ]
